<a href="https://colab.research.google.com/github/LeoMcBills/100-days-ML-Algo-Research/blob/main/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Torch basics

In [5]:
import torch
import numpy

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.6634e+37,  4.3692e-41,  5.6634e+37],
        [ 4.3692e-41, -6.6112e-30,  4.3691e-41],
        [-6.6113e-30,  4.3691e-41, -6.6197e-30],
        [ 4.3691e-41, -6.6198e-30,  4.3691e-41],
        [-6.6199e-30,  4.3691e-41, -6.6199e-30]])


In [3]:
my_list = [1, 2, 3]
x_tensor = torch.tensor(my_list)

print(x_tensor)

tensor([1, 2, 3])


In [4]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


## Torch tensor to numpy

In [6]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
