<a href="https://colab.research.google.com/github/LeoMcBills/100-days-ML-Algo-Research/blob/main/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Torch basics

In [ ]:
import torch
import numpy

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.6634e+37,  4.3692e-41,  5.6634e+37],
        [ 4.3692e-41, -6.6112e-30,  4.3691e-41],
        [-6.6113e-30,  4.3691e-41, -6.6197e-30],
        [ 4.3691e-41, -6.6198e-30,  4.3691e-41],
        [-6.6199e-30,  4.3691e-41, -6.6199e-30]])


In [ ]:
my_list = [1, 2, 3]
x_tensor = torch.tensor(my_list)

print(x_tensor)

tensor([1, 2, 3])


In [ ]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


## Torch tensor to numpy

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


# Auto Grad

In [1]:
import torch

x = torch.randn(3, requires_grad=True)
x

tensor([-0.4203, -0.3532, -1.4574], requires_grad=True)

In [2]:
print(x)

tensor([-0.4203, -0.3532, -1.4574], requires_grad=True)


In [6]:
y = x + 2
print(y)
z = y*y*2
z = z.mean()
n = z.mean()
print(z)
print(n)

tensor([1.5797, 1.6468, 0.5426], grad_fn=<AddBackward0>)
tensor(3.6680, grad_fn=<MeanBackward0>)
tensor(3.6680, grad_fn=<MeanBackward0>)


In [7]:
z.backward()
print(x.grad)

tensor([2.1063, 2.1957, 0.7235])


# Masking away the gradients

In [8]:
x = torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([-0.8845,  1.3579, -1.1798], requires_grad=True)
tensor([-0.8845,  1.3579, -1.1798])


In [9]:
# Second method
y = x.detach()
print(y)

tensor([-0.8845,  1.3579, -1.1798])


In [10]:
# Third method
with torch.no_grad():
  y = x + 2
  print(y)

tensor([1.1155, 3.3579, 0.8202])


## Time to demo a training loop

In [13]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Calculating gradients

In [16]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

# Forward pass and compute the loss
y_hat = w * x

# Loss
loss = (y_hat - y)**2

# compute gradient
loss.backward()
print(w.grad)

tensor(-2.)


# Gradients in linear regression with numpy

In [17]:
import numpy as np

In [18]:
x = np.array([1, 2, 3, 4], dtype=np.float32)

In [19]:
y = x * 2

In [20]:
y

array([2., 4., 6., 8.], dtype=float32)

In [21]:
w = 0.0

# model prediction
def forward(x):
  return w * x

In [22]:
# loss
def loss(y, y_predicted):
  return ((y_predicted-y)**2).mean()

In [23]:
# gradient
def gradient(x,y, y_predicted):
  return np.dot(2*x, y_predicted-y).mean()

In [24]:
print(f'Prediction before training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000


In [28]:
# Training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  y_pred = forward(x)

  # loss
  l = loss(y, y_pred)

  # gradients
  dw = gradient(x, y, y_pred)

  # update weights
  w -= learning_rate * dw

  if epoch % 1 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

epoch 1: w = 2.000, loss = 0.00000033
epoch 2: w = 2.000, loss = 0.00000005
epoch 3: w = 2.000, loss = 0.00000001
epoch 4: w = 2.000, loss = 0.00000000
epoch 5: w = 2.000, loss = 0.00000000
epoch 6: w = 2.000, loss = 0.00000000
epoch 7: w = 2.000, loss = 0.00000000
epoch 8: w = 2.000, loss = 0.00000000
epoch 9: w = 2.000, loss = 0.00000000
epoch 10: w = 2.000, loss = 0.00000000
epoch 11: w = 2.000, loss = 0.00000000
epoch 12: w = 2.000, loss = 0.00000000
epoch 13: w = 2.000, loss = 0.00000000
epoch 14: w = 2.000, loss = 0.00000000
epoch 15: w = 2.000, loss = 0.00000000
epoch 16: w = 2.000, loss = 0.00000000
epoch 17: w = 2.000, loss = 0.00000000
epoch 18: w = 2.000, loss = 0.00000000
epoch 19: w = 2.000, loss = 0.00000000
epoch 20: w = 2.000, loss = 0.00000000


In [29]:
print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction after training: f(5) = 10.000


# Gradient descent with Autograd and Back propagation

In [30]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

In [31]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [32]:
def forward(x):
  return w * x

In [33]:
def loss(y, y_predicted):
  return ((y_predicted-y)**2).mean()

In [34]:
print(f'Prediction before training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000


In [36]:
learning_rate = 0.01
n_iters = 100

In [37]:
for epoch in range(n_iters):
  y_pred = forward(x)
  l = loss(y, y_pred)
  l.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad

  w.grad.zero_()
  if epoch % 10 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction before training: f(5) = {forward(5):.3f}')

epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction before training: f(5) = 10.000
